version: '2'
services:
    webcrawler:
        build: .
        restart: always
        environment:
            - WEBCRAWLER_MAX_THREADS=10
        ports:
            - "8080:8080"
        volumes:
            - /logs
